### PR TITLE
feature: ability to drag and drop images into editor 

### PR DESCRIPTION
**Pull request by khakimov**
drap and drop feature (#16) and also allowing to add multiply images (`multiSelections`). added `milliseconds` to filename, otherwise its too quick and overwriting multiple images.

### CODE REVIEW

**Comment by UdaraJay** [comment]
this is great! 🙌

**Comment by khakimov** [comment]
@UdaraJay let me test a little bit more, found a bug 🐞

**Comment by khakimov** [comment]
good to go. 

drag and drop ✅:
image

copy/paste files ✅:
image

**Comment by UdaraJay** [comment]
hey @khakimov 👋  was there a reason you closed this? feel free to reopen if it's ready and I'll merge into next release.

**Comment by khakimov** [comment]
> hey @khakimov 👋 was there a reason you closed this? feel free to reopen if it's ready and I'll merge into next release.

ah, i saw the merge and thought it was merged already. reopened and ready to merge.

**Pull request merged**
